# 基础镜像
FROM redis
# author
MAINTAINER dirt

# 挂载目录
VOLUME /home/dirt/redis
# 创建目录
RUN mkdir -p /home/dirt/redis
# 指定路径
WORKDIR /home/dirt/redis
# 复制conf文件到路径
COPY ./conf/redis.conf /home/dirt/redis/redis.conf
