# 基础镜像
FROM nginx
# author
MAINTAINER dirt

# 挂载目录
VOLUME /home/dirt/projects/dirt-ui
# 创建目录
RUN mkdir -p /home/dirt/projects/dirt-ui
# 指定路径
WORKDIR /home/dirt/projects/dirt-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/dirt/projects/dirt-ui
