
spring:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false


    properties:
      hibernate:
        # 为解决问题： no Session; nested exception is com.fasterxml.jackson.databind.JsonMappingException
        enable_lazy_load_no_trans: true
  data:
    redis:
      repositories:
        # 禁止警告 Spring Data Redis - Could not safely identify store assignment for repository candidate interface
        enabled: false
  cache:
    type: redis
    redis:
      # 60 secs
      time-to-live: 60000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
  profiles:
    active: mysqlfk


zk:
  snowflake:
    nodeId: 257
#server:
#  servlet:
#    context-path: /member-script
server:
  port: 8084

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30




#管理端点
management:
  #server:
  #  port: 7001
  #  address: 127.0.0.1
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        #include:   "*"
        include:
          - info
          - health
          - loggers
          - mappings
          - beans
          - env
          - shutdown
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.jdbc: info
    # 打印请求日志
    com.zk.config.rest.aspect.LogReqResAspect: debug

knife4j:
  # 开启增强配置
  enable: true
  # 开启生产环境屏蔽
  production: false

dirt:
  enable: true
