# 基础镜像
FROM  openjdk:8-jre
# author
MAINTAINER dirt

# 挂载目录
VOLUME /home/dirt
# 创建目录
RUN mkdir -p /home/dirt
# 指定路径
WORKDIR /home/dirt
# 复制jar文件到路径
COPY ./jar/dirt-modules-system.jar /home/dirt/dirt-modules-system.jar
# 启动系统服务
ENTRYPOINT ["java","-jar","dirt-modules-system.jar"]